### ISSUE TITLE
Use question

### ISSUE THREAD

**Issue by ageorge303** [gesellix-docker/gradle-docker-plugin#26]
We're successfully using the plugin to build and push images from local development boxes to the main docker hub. We can pull those images back down to our local development machines with the plugin. What we need to do is be able to pull those images down to a workstation.

The workstation has just a single user (root), but my docker credentials (from doing docker login for 'ageorge' on that machine) are cached in ~root/.dockercfg.

When trying to create the image on the workstation, it's doing this:
POST /images/create?fromImage=xxxx%2Fyyyy-api&tag=latest&registry= HTTP/1.1
and fails with this error:
[de.gesellix.docker.client.DockerResponseHandler] [error:Error: image xxxx/yyyy-api:latest not found, errorDetail:[message:Error: image xxxx/yyyy-api:latest not found]]

How would I see what credentials it's trying create the image with on the workstation?

Thanks.

**Comment by gesellix** [comment]
@ageorge303 are the images you're trying to pull in a public or in a private repository? If they're in a public repository you won't need any credentials for a pull. The error looks to me more like a missing default in the plugin. Could you try to set the registry property?
I can have a look at it tonight.

**Comment by ageorge303** [comment]
Tobias,
The repo is private on the docker hub.

**Comment by ageorge303** [comment]
Registry property?

**Comment by gesellix** [comment]
@ageorge303 forget the registry property - there's a missing feature to pass your credentials to the pull command. I'll add it asap, probably this week.

**Comment by ageorge303** [comment]
Wonderful. Thanks.

**Comment by gesellix** [comment]
@ageorge303 please give https://plugins.gradle.org/plugin/de.gesellix.docker/2015-04-11T22-32-01 a  try, an example use case is available at https://github.com/gesellix-docker/gradle-docker-plugin-example/blob/master/push-and-pull-with-auth/build.gradle

The current implementation doesn't allow the plugin to transparently choose your credentials, so that you have to manually configure your tasks. I'm open for feedback, and if you have some suggestions please just leave me note here. Thanks!

**Comment by ageorge303** [comment]
Thank you. Works great.

**Comment by ageorge303** [comment]
I was able to pull an image to a remote server from the Docker hub. Great!

However, my buildImage task is now broken.
I get the following error:

 Task has not declared any outputs.
docker build
temporary buildContext: /home/ageorge/repos/psb-api/src/generated/server/build/tmp/buildImage/buildContext_xxxx.tar.gz
docker build
using docker at 'unix:///var/run/docker.sock'
:buildImage FAILED
:buildImage (Thread[main,5,main]) completed. Took 0.15 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> java.net.MalformedURLException: unknown protocol: unix

**Comment by ageorge303** [comment]
ext {
  localDockerHost = "unix:///var/run/docker.sock"
  remoteDockerHost = "http://machine.blah.net:2375"
  ...
}

task buildImage(type: DockerBuildTask) {
  //dependsOn rmImage
  dependsOn copyWARToBuildContext

  dockerHost = localDockerHost
  imageName = appName

  buildContextDirectory = file("./docker/")
}

**Comment by ageorge303** [comment]
Caused by: java.net.MalformedURLException: unknown protocol: unix
	at de.gesellix.docker.client.protocolhandler.DockerURLHandler.getURLWithActualProtocol(DockerURLHandler.groovy:57)
	at de.gesellix.docker.client.protocolhandler.DockerURLHandler$getURLWithActualProtocol$0.callCurrent(Unknown Source)
	at de.gesellix.docker.client.protocolhandler.DockerURLHandler.getURL(DockerURLHandler.groovy:30)
	at de.gesellix.docker.client.protocolhandler.DockerURLHandler$getURL.call(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.getDockerBaseUrl(LowLevelDockerClient.groovy:43)
	at de.gesellix.docker.client.LowLevelDockerClient.openConnection(LowLevelDockerClient.groovy:260)
	at de.gesellix.docker.client.LowLevelDockerClient.request(LowLevelDockerClient.groovy:69)
	at de.gesellix.docker.client.LowLevelDockerClient$request$1.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.post(LowLevelDockerClient.groovy:57)
	at de.gesellix.docker.client.LowLevelDockerClient$post.call(Unknown Source)
	at de.gesellix.docker.client.DockerClientImpl.build(DockerClientImpl.groovy:137)
	at de.gesellix.docker.client.DockerClientImpl.build(DockerClientImpl.groovy)
	at de.gesellix.docker.client.DockerClient$build.call(Unknown Source)
	at de.gesellix.gradle.docker.tasks.DockerBuildTask.build(DockerBuildTask.groovy:91)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)

**Comment by gesellix** [comment]
@ageorge303 unix sockets should work, but I'll check them during the weekend. Would you be so kind and open a dedicated issue for this? That would be great, thanks!

**Comment by gesellix** [comment]
@ageorge303 which jdk and which version do you use? Unix socket support currently relies on the `sun.net.www.protocol.http.HttpURLConnection` class, which is probably only available in the official Oracle JDK.
