### ISSUE TITLE
Pulling to remote server works with http, not https

### ISSUE THREAD

**Issue by ageorge303** [gesellix-docker/gradle-docker-plugin#33]
Pulling an image from docker hub to a remote server. It works fine when the remote host docker daemon is running thus:
/usr/bin/docker -d -H fd:// -H tcp://0.0.0.0:2375

Attempted to run daemon with https:
curl https://xxxx.yyy.net:2376/images/json --cert ~/.docker/cert.pem --key ~/.docker/key.pem --cacert ~/.docker/ca.pem
Added certificates to /root/.docker (ca.pem, key.pem, cert.pem) and was about to curl to that daemon from another machine.

docker pull
docker pull 'aaaa/bbbb:latest'
using docker at 'https://xxxx.yyy.net:2376'
POST https://xxxx.yyy.net:2376/images/create?fromImage=aaaa%2Fbbbb&tag=latest&registry=null using proxy: DIRECT
:deployToServer FAILED
:deployToServer (Thread[main,5,main]) completed. Took 0.509 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deployToServer'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
  	[class java.lang.String]
  	[class java.net.URI]

**Comment by gesellix** [comment]
can you run it with `-s` to produce a stracktrace? thanks!

**Comment by ageorge303** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':deployToServer'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
Caused by: groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.net.URI]
	at de.gesellix.docker.client.LowLevelDockerClient.initSSLSocketFactory(LowLevelDockerClient.groovy:291)
	at de.gesellix.docker.client.LowLevelDockerClient$initSSLSocketFactory$4.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.configureSSL(LowLevelDockerClient.groovy:282)
	at de.gesellix.docker.client.LowLevelDockerClient$configureSSL$3.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.configureConnection(LowLevelDockerClient.groovy:277)
	at de.gesellix.docker.client.LowLevelDockerClient.request(LowLevelDockerClient.groovy:70)
	at de.gesellix.docker.client.LowLevelDockerClient$request$1.callCurrent(Unknown Source)
	at de.gesellix.docker.client.LowLevelDockerClient.post(LowLevelDockerClient.groovy:57)
	at de.gesellix.docker.client.LowLevelDockerClient$post.call(Unknown Source)
	at de.gesellix.docker.client.DockerClientImpl.pull(DockerClientImpl.groovy:222)
	at de.gesellix.docker.client.DockerClient$pull$2.call(Unknown Source)
	at de.gesellix.gradle.docker.tasks.DockerPullTask.pull(DockerPullTask.groovy:32)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 47 more


BUILD FAILED

**Comment by gesellix** [comment]
could you try the most recent version? It is available at

* bintray: https://bintray.com/gesellix/docker-utils/gradle-docker-plugin/_latestVersion
* plugin portal: https://plugins.gradle.org/plugin/de.gesellix.docker

**Comment by gesellix** [comment]
@ageorge303 this one should be fixed, too.

**Comment by gesellix** [comment]
@ageorge303 closing for now, if you still get the same problem, just reopen this issue. Thanks!
