### ISSUE TITLE
No such property: Id for class: de.gesellix.docker.client.DockerResponse

### ISSUE THREAD

**Issue by reaperdk** [gesellix-docker/gradle-docker-plugin#34]
Hi,

Firstly - great job with gradle docker plugin!

Secondly - since I changed 'de.gesellix.docker' plugin version from "2015-04-15T07-27-27" to "2015-04-25T09-55-20" exec task is not working correctly. I am receving message "No such property: Id for class: de.gesellix.docker.client.DockerResponse". Here is build result with --stacktrace option:

```
...
[INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :super-cool-project:exec (Thread[main,5,main]) started.
[LIFECYCLE] [class org.gradle.TaskExecutionLogger] :super-cool-project:exec
[DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':super-cool-project:exec'
[DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':super-cool-project:exec' is up-to-date
[INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':super-cool-project:exec' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
[DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':super-cool-project:exec'.
[INFO] [de.gesellix.gradle.docker.tasks.DockerExecTask] docker exec
[DEBUG] [de.gesellix.gradle.docker.tasks.DockerExecTask] exec cmd: '[sh, -c, /entrypoint.sh]'
[INFO] [de.gesellix.docker.client.DockerClientImpl] docker create exec on 'super-cool-project'
[INFO] [de.gesellix.docker.client.DockerClientImpl] using docker at 'http://remotedocker:2375'
[DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] certsPathExists=false, isTlsPort=false
[DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] assume 'http'
[DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] selected dockerHost at 'http://remotedocker:2375'
[INFO] [de.gesellix.docker.client.LowLevelDockerClient] POST http://remotedocker:2375/containers/super-cool-project/exec using proxy: DIRECT
[DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@8eb31010 pairs: {POST /containers/super-cool-project/exec HTTP/1.1: null}{charset: utf-8}{Content-Type: application/json}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_31}{Host: remotedocker:2375}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 111}
[DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@bc95734 pairs: {null: HTTP/1.1 201 Created}{Content-Type: application/json}{Date: Tue, 28 Apr 2015 08:23:20 GMT}{Content-Length: 74}
[INFO] [de.gesellix.docker.client.LowLevelDockerClient] status: [HTTP/1.1 201 Created]
[DEBUG] [de.gesellix.docker.client.LowLevelDockerClient] headers: [content-length:[74], date:[Tue, 28 Apr 2015 08:23:20 GMT], content-type:[application/json]]
[INFO] [de.gesellix.docker.client.DockerResponseHandler] won't search for errors in null
[DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':super-cool-project:exec'
[LIFECYCLE] [class org.gradle.TaskExecutionLogger] :super-cool-project:exec FAILED
[INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :super-cool-project:exec (Thread[main,5,main]) completed. Took 0.014 secs.
[DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 3.089 secs, idle: 0.003 secs
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
[ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':super-cool-project:exec'.
[ERROR] [org.gradle.BuildExceptionReporter] > No such property: Id for class: de.gesellix.docker.client.DockerResponse
[ERROR] [org.gradle.BuildExceptionReporter]
[ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
[ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':super-cool-project:exec'.
[ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
[ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
...
[ERROR] [org.gradle.BuildExceptionReporter] Caused by: groovy.lang.MissingPropertyException: No such property: Id for class: de.gesellix.docker.client.DockerResponse
[ERROR] [org.gradle.BuildExceptionReporter]        at de.gesellix.gradle.docker.tasks.DockerExecTask.exec(DockerExecTask.groovy:44)
```

I think it is wrongly detecting error in exec request's response. Here is request:
```
POST /containers/super-cool-project/exec HTTP/1.1
charset: utf-8
Content-Type: application/json
Cache-Control: no-cache
Pragma: no-cache
User-Agent: Java/1.8.0_31
Host: localhost:2375
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 111

{"AttachStdin":false,"AttachStdout":true,"AttachStderr":true,"Tty":false,"Cmd":["sh","-c","/entrypoint.sh"]}
```
And the response:
```
HTTP/1.1 201 Created
Content-Type: application/json
Date: Tue, 28 Apr 2015 08:34:42 GMT
Content-Length: 74

{"Id":"eec5a46782a4bc1c81e826cc6495877628e2688e3ba01803fac7700f9690cf4a"}
```

Hope it will help you to resolve the problem :)

**Comment by gesellix** [comment]
thanks for reporting, the issue should be fixed with the just released update :)

**Comment by reaperdk** [comment]
Thankx :+1:
