### ISSUE TITLE
buildImage not working again

### ISSUE THREAD

**Issue by ageorge303** [gesellix-docker/gradle-docker-plugin#36]
The buildImage task is not working again. I'm using this
id "de.gesellix.docker" version "2015-05-25T16-45-10".
In the past, I was able to use  version "2015-03-07T20-17-57", but this version doesn't work now either.

From the log file:
```
15:15:58.483 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :buildImage FAILED
15:15:58.484 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :buildImage (Thread[main,5,main]) completed. Took 1.302 secs.
15:15:58.485 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 4.084 secs, idle: 0.007 secs
15:15:58.499 [ERROR] [org.gradle.BuildExceptionReporter] 
15:15:58.501 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:15:58.503 [ERROR] [org.gradle.BuildExceptionReporter] 
15:15:58.503 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:15:58.504 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':buildImage'.
15:15:58.505 [ERROR] [org.gradle.BuildExceptionReporter] > org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)
15:15:58.507 [ERROR] [org.gradle.BuildExceptionReporter] 
15:15:58.508 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:15:58.509 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildImage'.
15:15:58.510 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:15:58.511 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:15:58.512 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:15:58.513 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:15:58.514 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:15:58.515 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
15:15:58.516 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:15:58.518 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:15:58.519 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:15:58.519 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
15:15:58.520 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
15:15:58.522 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
15:15:58.523 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
15:15:58.524 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
15:15:58.525 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
15:15:58.526 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
15:15:58.527 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:15:58.528 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
15:15:58.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
15:15:58.529 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:15:58.530 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:15:58.531 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
15:15:58.532 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
15:15:58.533 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
15:15:58.534 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
15:15:58.534 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
15:15:58.535 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
15:15:58.536 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
15:15:58.537 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
15:15:58.538 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
15:15:58.539 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
15:15:58.540 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
15:15:58.541 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
15:15:58.542 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
15:15:58.543 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:15:58.544 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:15:58.545 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
15:15:58.546 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:15:58.547 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:15:58.548 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:15:58.549 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
15:15:58.550 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:15:58.551 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:15:58.552 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:15:58.553 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:15:58.553 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
15:15:58.554 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
15:15:58.555 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
15:15:58.556 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.gradle.internal.UncheckedException: org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)
15:15:58.557 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:39)
15:15:58.558 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:66)
15:15:58.559 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
15:15:58.560 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
15:15:58.561 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
15:15:58.562 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
15:15:58.563 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
15:15:58.564 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:15:58.565 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:15:58.566 [ERROR] [org.gradle.BuildExceptionReporter] 	... 47 more
15:15:58.566 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.newsclub.net.unix.AFUNIXSocketException: No such file or directory (socket: /run/docker.sock)
15:15:58.567 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
15:15:58.568 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:134)
15:15:58.569 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:97)
15:15:58.570 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.newsclub.net.unix.AFUNIXSocket$connect$0.call(Unknown Source)
15:15:58.571 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.socketfactory.unix.UnixSocketFactory.connectSocket(UnixSocketFactory.groovy:54)
15:15:58.572 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.conn.socket.ConnectionSocketFactory$connectSocket.callCurrent(Unknown Source)
15:15:58.573 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.socketfactory.unix.UnixSocketFactory.connectSocket(UnixSocketFactory.groovy:88)
15:15:58.574 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:178)
15:15:58.575 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
15:15:58.576 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
15:15:58.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
15:15:58.577 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
15:15:58.578 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
15:15:58.579 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:214)
15:15:58.580 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
15:15:58.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
15:15:58.581 [ERROR] [org.gradle.BuildExceptionReporter] 	at groovyx.net.http.RESTClient.post(RESTClient.java:141)
15:15:58.582 [ERROR] [org.gradle.BuildExceptionReporter] 	at groovyx.net.http.RESTClient$post.call(Unknown Source)
15:15:58.583 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.docker.client.DockerClientImpl.build(DockerClientImpl.groovy:82)
15:15:58.584 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.docker.client.DockerClientImpl.build(DockerClientImpl.groovy)
15:15:58.585 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.docker.client.DockerClient$build.call(Unknown Source)
15:15:58.586 [ERROR] [org.gradle.BuildExceptionReporter] 	at de.gesellix.gradle.docker.tasks.DockerBuildTask.build(DockerBuildTask.groovy:95)
15:15:58.587 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
15:15:58.588 [ERROR] [org.gradle.BuildExceptionReporter] 	... 54 more
15:15:58.588 [ERROR] [org.gradle.BuildExceptionReporter] 
15:15:58.589 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:15:58.590 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:15:58.591 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:15:58.592 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 14.025 secs

```

**Comment by ageorge303** [comment]
Please delete. Idiocy abounds. :)
